{% set name = "bgen-reader" %}
{% set version = "3.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 94443a59a52ff61039f343a158f5ab5587093e2334f7525e10e243010d1dbb13

build:
  number: 0
  skip: true  # [py27]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - bgen >=3.0.2
    - cffi >=1.11.5
    - pip
    - pytest-runner >=4.2
    - python
    - setuptools >=38.4.0
  run:
    - bgen >=3.0.2
    - cffi >=1.11.5
    - dask >=1.0.0
    - pandas >=0.23.4
    - pytest >=3.3.2
    - pytest-runner >=4.2
    - python
    - scipy >=1.1.0
    - toolz >=0.9.0
    - tqdm >=4.19.5
    - xarray >=0.11.2
    - texttable >=1.5.0
    - cachetools >=3.0.0

test:
  requires:
    - pytest
  imports:
    - pandas
    - bgen_reader
  commands:
    - python -c "import sys; import pandas; import bgen_reader; sys.exit(bgen_reader.test())"

about:
  home: http://github.com/limix/{{ name }}-py
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'A BGEN file format reader'
  description: |
    BGEN is a file format for storing large genetic datasets.
    It supports both unphased genotypes and phased haplotype data with variable
    ploidy and number of alleles. It was designed to provides a compact data
    representation without sacrificing variant access performance.
  doc_url: https://bgen-reader.readthedocs.io
  dev_url: https://github.com/limix/{{ name }}-py

extra:
  recipe-maintainers:
    - Horta
