{% set version = "2.0.8" %}

package:
  name: bgen_reader
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/bgen-reader/bgen-reader-{{ version }}.tar.gz
  sha256: 801f217e4f22fe5acc67c09b47af1ce9f5e944c039b9b544420ca8fe20895542

build:
  number: 0
  skip: true  # [win and py27]
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - bgen >=2.0.3
    - cffi >=1.11.4
    - pip
    - pytest-runner >=3.0
    - python
    - setuptools >=38.4.0
  run:
    - bgen >=2.0.3
    - cffi >=1.11.4
    - dask >=0.16.1
    - pandas >=0.22.0
    - pytest >=3.3.2
    - python
    - scipy >=1.0.1
    - toolz >=0.9.0
    - tqdm >=4.19.5
    - xarray >=0.10.7
    - texttable >=1.5.0
    - cachetools >=3.0.0

test:
  requires:
    - pytest
  imports:
    - pandas
    - bgen_reader
  commands:
    - python -c "import sys; import pandas; import bgen_reader; sys.exit(bgen_reader.test())"

about:
  home: https://github.com/limix/bgen-reader-py
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'A BGEN file format reader'
  description: |
    BGEN is a file format for storing large genetic datasets.
    It supports both unphased genotypes and phased haplotype data with variable
    ploidy and number of alleles. It was designed to provides a compact data
    representation without sacrificing variant access performance.
  doc_url: https://github.com/limix/bgen-reader-py
  dev_url: https://github.com/limix/bgen-reader-py

extra:
  recipe-maintainers:
    - Horta
